# Generated by Django 5.2.15 on 2026-06-20 20:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("historial_clinico", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AntecedentePaciente",
            fields=[
                (
                    "id_antecedente",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "tipo_antecedente",
                    models.CharField(
                        choices=[
                            ("PATOLOGICO", "Patológico"),
                            ("NO_PATOLOGICO", "No Patológico"),
                            ("FAMILIAR", "Familiar"),
                            ("QUIRURGICO", "Quirúrgico"),
                            ("ALERGICO", "Alérgico"),
                            ("OTRO", "Otro"),
                        ],
                        default="PATOLOGICO",
                        max_length=30,
                    ),
                ),
                ("descripcion", models.TextField()),
                (
                    "fecha_creacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "id_historial",
                    models.ForeignKey(
                        db_column="id_historial",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="antecedentes",
                        to="historial_clinico.historialclinico",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        db_column="registrado_por",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="antecedentes_registrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "antecedentes_paciente",
                "ordering": ["-fecha_creacion"],
                "indexes": [
                    models.Index(
                        fields=["id_historial"], name="idx_antecedente_historial"
                    ),
                    models.Index(
                        fields=["tipo_antecedente"], name="idx_antecedente_tipo"
                    ),
                ],
            },
        ),
    ]
