# Generated by Django 5.2.15 on 2026-06-20 15:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("especialistas", "0003_alter_especialista_options"),
        ("historial_clinico", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvolucionPaciente",
            fields=[
                (
                    "id_evolucion",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("nota_evolucion", models.TextField()),
                (
                    "fecha_creacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "id_especialista",
                    models.ForeignKey(
                        db_column="id_especialista",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evoluciones",
                        to="especialistas.especialista",
                    ),
                ),
                (
                    "id_historial",
                    models.ForeignKey(
                        db_column="id_historial",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evoluciones",
                        to="historial_clinico.historialclinico",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        db_column="registrado_por",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evoluciones_registradas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "evoluciones_paciente",
                "ordering": ["-fecha_creacion"],
                "indexes": [
                    models.Index(
                        fields=["id_historial"], name="idx_evolucion_historial"
                    ),
                    models.Index(
                        fields=["id_especialista"], name="idx_evolucion_especialista"
                    ),
                ],
            },
        ),
    ]
