# Generated by Django 5.2.15 on 2026-06-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bitacora", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bitacora",
            name="accion",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Inicio de sesión"),
                    ("LOGOUT", "Cierre de sesión"),
                    ("LOGIN_FALLIDO", "Login fallido"),
                    ("CREAR", "Crear registro"),
                    ("EDITAR", "Editar registro"),
                    ("ELIMINAR", "Eliminar registro"),
                    ("CAMBIAR_PASSWORD", "Cambio de contraseña"),
                    ("RECUPERAR_PASSWORD", "Recuperación de contraseña"),
                    ("REPROGRAMAR", "Reprogramar cita"),
                    ("CANCELAR", "Cancelar cita"),
                    ("CONFIRMAR", "Confirmar cita"),
                    ("ARCHIVAR", "Archivar registro"),
                    ("RESTAURAR", "Restaurar registro"),
                ],
                max_length=30,
            ),
        ),
    ]
