# Generated by Django 5.2.15 on 2026-06-20 19:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("consultas", "0002_cu12_cu13_cu14_fields"),
        ("historial_clinico", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecetaMedicamento",
            fields=[
                ("id_receta", models.BigAutoField(primary_key=True, serialize=False)),
                ("medicamentos", models.JSONField()),
                ("indicaciones", models.TextField(blank=True, null=True)),
                (
                    "fecha_creacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "id_consulta",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_consulta",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recetas",
                        to="consultas.consultamedica",
                    ),
                ),
                (
                    "id_historial",
                    models.ForeignKey(
                        db_column="id_historial",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recetas",
                        to="historial_clinico.historialclinico",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        db_column="registrado_por",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recetas_registradas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "recetas_medicamentos",
                "ordering": ["-fecha_creacion"],
                "indexes": [
                    models.Index(fields=["id_historial"], name="idx_receta_historial"),
                    models.Index(fields=["id_consulta"], name="idx_receta_consulta"),
                ],
            },
        ),
    ]
